name: hugging-face
channels:
  - main
  - conda-forge
  - r
  - defaults
dependencies:
  - python=3.12
  - aiohappyeyeballs
  - aiohttp
  - aiosignal
  - arrow-cpp
  - attrs
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - aws-sdk-cpp
  - blas
  - blinker
  - boost-cpp
  - bottleneck
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - charset-normalizer
  - click
  - cyrus-sasl
  - datasets
  - diffusers
  - diffusers-base
  - diffusers-torch
  - dill
  - eigen
  - expat
  - ffmpeg
  - filelock
  - flask
  - fontconfig
  - freetype
  - frozenlist
  - fsspec
  - gettext
  - gflags
  - glib
  - glib-tools
  - glog
  - gmp
  - gnutls
  - graphite2
  - gst-plugins-base
  - gstreamer
  - harfbuzz
  - hdf5
  - huggingface_accelerate
  - huggingface_hub
  - icu
  - idna
  - importlib-metadata
  - itsdangerous
  - jinja2
  - jpeg
  - krb5
  - lame
  - lcms2
  - lerc
  - libabseil
  - libboost
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libclang
  - libclang13
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libevent
  - libffi
  - libgfortran
  - libgfortran5
  - libglib
  - libgrpc
  - libiconv
  - libidn2
  - libllvm14
  - libnghttp2
  - libopenblas
  - libopus
  - libpng
  - libpq
  - libprotobuf
  - libssh2
  - libtasn1
  - libthrift
  - libtiff
  - libunistring
  - libvpx
  - libwebp-base
  - libxml2
  - llvm-openmp
  - lz4-c
  - markupsafe
  - mpmath
  - multidict
  - multiprocess
  - mysql
  - ncurses
  - nettle
  - networkx
  - numexpr
  - numpy
  - numpy-base
  - opencv
  - openh264
  - openjpeg
  - openssl
  - orc
  - packaging
  - pandas
  - pcre2
  - pillow
  - pip
  - pixman
  - psutil
  - pyarrow
  - pysocks
  - python
  - python-dateutil
  - python-dotenv
  - python-tzdata
  - python-xxhash
  - pytorch
  - pytorch-cpu
  - pytz
  - pyyaml
  - qt-main
  - re2
  - readline
  - regex
  - requests
  - safetensors
  - setuptools
  - six
  - snappy
  - sqlite
  - sympy
  - tk
  - tokenizers
  - tqdm
  - transformers
  - typing-extensions
  - typing_extensions
  - tzdata
  - urllib3
  - utf8proc
  - werkzeug
  - wheel
  - x264
  - xxhash
  - xz
  - yaml
  - yarl
  - zipp
  - zlib
  - zstd
  - gunicorn
  - gevent
